# Generated by Django 3.1.7 on 2021-03-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersites',
            name='language',
            field=models.CharField(choices=[('af', 'Afrikaans'), ('am', 'Amharic\t'), ('bg', 'Bulgarian\t'), ('ca', 'Catalan\t'), ('zh-HK', 'Chinese (Hong Kong)\t'), ('zh-CN', 'Chinese (PRC)\t'), ('zh-TW', 'Chinese (Taiwan)\t'), ('hr', 'Croatian\t'), ('cs', 'Czech\t'), ('da', 'Danish\t'), ('nl', 'Dutch\t'), ('en-GB', 'English (UK)'), ('en-US', 'English (US)\t'), ('et', 'Estonian\t'), ('fil', 'Filipino\t'), ('fi', 'Finnish\t'), ('fr-CA', 'French (Canada)\t'), ('fr-FR', 'French (France)\t'), ('de', 'German\t'), ('el', 'Greek\t'), ('he', 'Hebrew\t')], default='el', max_length=5),
        ),
    ]
