# Generated by Django 3.1.5 on 2021-03-06 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersites', '0003_auto_20210303_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwords', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersites.usersites')),
            ],
            options={
                'verbose_name_plural': 'multikwords',
            },
        ),
    ]
